spring:
  profiles:
    active: dev
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:8889/
      label: main
  config:
    import: optional:configserver:http://localhost:8889/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
    register-with-eureka: true
  instance:
    preferIpAddress: true